name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    name: Terraform
    uses: FollowTheProcess/ci/.github/workflows/Terraform.yml@v3
    permissions:
      contents: read
